<?php
/**
 * Implements hook_field_schema().
 */
function flag_entity_field_schema($field) {
  switch($field['type']) {
    case 'flag_entity_fields_flag':
      $columns = array(
        'flagable' => array(
          'description' => 'Data indicating whether the entity should be flaged or not.',
          'type' => 'text',
          'not null' => FALSE,
        )
      );
      $indexes = array();
    break;
  }
  return array(
    'columns' => $columns,
    'indexes' => $indexes,
  );
}

